### PR TITLE
Tutorial writing and publishing a C++ gRPC service

### PR DESCRIPTION
**Pull request by andre-senna**

### CODE REVIEW

**Comment by ferrouswheel** [comment]
I'm a little worried that our tutorials are wrapping up the important details in shell scripts (e.g. publishAndStartService.sh). These might be useful for us, but they hide the platform details that are important for showing a tutorial user how things work.

**Comment by andre-senna** [comment]
Perhaps this can be mitigated by writing explanatory comments in the scripts?

**Comment by ferrouswheel** [comment]
If this is meant to be a tutorial or documentation, then I don't think hiding stuff in scripts, even if they are documented, is the right approach.

If we need special scripts, then to me this suggests there is something wrong with the CLI usability and the CLI should be fixed, or these helper scripts should be bundled with the CLI somehow.

**Comment by andre-senna** [comment]
Scripts are not actually needed. They are just helpers which serve two purposes:

(1) Allow developers to quickly do something that works. I think this is important. I believe it can be discouraging if people need to do a lot of simple configuration steps (such the ones scripted in publishAndStartService.sh you mentioned) before having something that works. Once it starts working in its own project, he/she will probably want to better understand the gory details and so may want to figure out what those scripts do.

(2) The scripts build a skeleton project structure. Including a script to 'build' and another one to 'run" the project. This is useful (again) to (a) help the new developer guiding it to make a good project structure when developing its own project and (b) allow us to evolve (in the future) the scripts into a better structured tool to create/manage projects.

**Comment by andre-senna** [comment]
Joel: "However, reading it as a tool that generates a project from a template makes more sense. 
In this case I would probably make a separate directory of templates for each language. Such a tool I think is different to a tutorial that's trying to educate the reader on using SNet."

Yes the idea is having a tutorial for each language and the common parts refactored to be reused in each tutorial. Those "common parts" will probably become a tutorial to educate readers to use SNet. We are already working on this and will have (by the end of next week) tutorials for C++, Python, Go and Java. 

I've decided to publish our unfinished job because I know there are colleagues implementing new services and I believe the tutorials (and helper scripts) may be useful.

**Comment by ferrouswheel** [comment]
Cool, that all makes sense to me :-)

> I believe it can be discouraging if people need to do a lot of simple configuration steps

Absolutely - and I think that the CLI should eventually be refactored to make the workflow simpler. But this is probably easiest to do after things settle down and using the scripts in your template services will make it clear what those steps are.

**Pull request merged**
